### PR TITLE
mostly thoughts on player & universe ID's

### PR DESCRIPTION
**Pull request by mikeford1**
I was wondering how to have fleets know who their owners are and how they can check their owner's diplomatic stances, so have had a go at creating a global dict containing the IDs, putting the universe and player IDs  but with a way to distinguish between them, and some functions to ensure that the keys aren't reused. I'm not sure how it would interact with the game.py tmpDicts that hold the "playerX" key dicts as these only exist within the Game class scope

### CODE REVIEW

**Comment by jurlaub** [comment]
The universe and player ID need improvement but I have some concerns with this approach. Right now Universe ID’s are an int (or maybe a string representation of an int). From a  human readability perspective, it may be better to be like the Player ID. Player ID is a string (‘player’ + n). They are generically numbered (similar to Stars) for anonymous play.  The only unique part of the Player ID is the number. ‘Attaching’ this number to a fleet ID would be essential to quickly identify Player ownership.  (Bit masking comes to mind but this may not be helpful in Python. )  A fleet identifier should not have a Universe ID as a part of its Fleet ID. (Primarily because fleets should be able to move between universes. )

Universes and Player UI’s should not share the same “namespace” as they have separate scope. Players can ‘own’ objects in one or all universes. Each Universe will hold items only within its ‘space.’ If something (say a fleet) transfers between Universes, it needs to happen at the universe class or game object level. Such a transfer should not involve modifying a Fleet UI. Transfers between players would result in a new Fleet UI.

Fleets have a potential conflict with UI’s. They should seemingly be unique but at the same time each player has a 0 - n fleets -  numbered in the same range. Rather then try to juggle two id’s it would be better to design the UI so that the Fleet number, presented to the player, 'masks' away the player UI portion. (While 512 was a hard limit for the original, it would also seem reasonable that a fleet boundary like this would be definable by the Game host.) The simplest way to achieve the merging of Player # and  Fleet UI is to use a string as the UI. 

One downside with this approach is the difficulty of finding the ‘next open fleet number.’ Fleet numbers change when a player merges and splits fleets, which could be challenging within a ‘string’ id context. Fleet numbers must both identify and provide capacity limits. To me that says ‘array’ and more specifically a bit array. With ‘next fleet number’ identified by the bit array, using either a string or number for the UI would be simple (but I think a string may still be simpler). I am hoping there is a more elegant and effective approach but cannot think of one at the moment. What ever is chosen needs to be used by both the StarsCoreEngine and client. 

With this in mind, I think the proposed changes to glob_vars.py only impact Universe and Player UI. The changes do not seem to be addressing the fleet ID concern. I don’t see a clear argument or benefit in making that change. 

FYI - The Stance class in player should probably be a player class ’tuple.’ That way all players would have access to the same elements and any change to the list would impact all player objects. An alternative could be to have the tuple in a diplomacy.py object. It could be used very similarly to a class - without a new class overhead.

**Comment by jurlaub** [comment]
Closing request

**Comment by mikeford1** [comment]
I'm not completely clear what a universe is? Looking at 
stars_engine_core_structure_v2_shared I thought there was a Universe 
that own things that aren't owned by players (MT + ??) and contains the "Universe 
Definition and Rules". Am I 
better thinking of the universe as a discrete z variable for 3d space 
(that happens to own a few things in it as well)? In terms of the assignment of players to a universe in game.py, is that simply spreading the homeworlds out or does a player being inside a universe mean something?


Date: Thu, 1 Jan 2015 20:21:37 -0800

**Comment by jurlaub** [comment]
I updated the internal structure document to capture the universe object. The initial diagram did not include a universe object. The idea of a 'universe' in stars is new. Its like the stars version of a 'multi-verse' holding all planets and space objects. Players are not really assigned to the universe as much as their HW's start in a Universe. The host may specify the number of players that can start inside a universe. I wanted to build the universe concept in from the beginning. Any player interaction would have to be developed after the core game was completed. 

Hopefully this is a better version of the current structure. (Player, Universe, & Tech) all are held within the Game Object. The host can use the command line to generate a new game (potentially using custom files), or load an existing game and generate a turn. The command line opens the file (.hst) which unpickels a game object. That object is then sent into the Order_Of_Events.py file, which processes the turn. Finally the associated files are saved/updated. 
[Version 3 StarsCoreEngine Internal Structure](https://docs.google.com/drawings/d/1SYeF5Nqv9q2Qbz7fi8CSOla2k0hb4tVKVT_i5oyf0yw/edit?usp=sharing)

Hopefully this provides some insight into some of the object inheritance. 
[Some Object Inheritance](https://docs.google.com/drawings/d/1yL6nYDkCPafbsbJY0jreaKzPb1zfNLJQuAxSHbmPFhI/edit?usp=sharing)

**Comment by mikeford1** [comment]
Thanks, I'm a bit clearer now.

How do you envision the relationship between different universes, how do (fleets only?) move between them, what difference does it make if a player has colonies on planets owned by different universes? 
    

Date: Mon, 5 Jan 2015 23:37:50 -0800

**Comment by jurlaub** [comment]
At the moment, my approach to go with the solution providing the simplest of functionality, considering the drastic nature of the change.

Fleet travel between universes would be (initially, until other enhancements are made after the initial ‘code complete’ objective) by wormhole only. 

A players colonies would not be affected. The player object holds a dictionary of colonies. Each colony has a reference to a planet object. (Colonies are separate and do not inherit from the planet). The planet objects have unique identifiers - even though they are also only connected/accessible via a single universe. (currently, the id is universe number + '_' + planet number.)

**Pull request closed without merging**
